version: '3.8'

services:
  neo4j:
    image: neo4j:4.4-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  loan-approval:
    build:
      context: ./apps/loan-approval
    ports:
      - "8083:8083"
    depends_on:
      - neo4j
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password

  risk-model:
    build:
      context: ./services/risk-model
    ports:
      - "8084:8084"
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password

volumes:
  neo4j-data:
  neo4j-logs: 